import { useEffect, useRef, useState } from 'react';
import styles from './poly-app-case-study.module.css';
const chapters = [['mobile-shift', 'The mobile shift'], ['core-tracking', 'Core tracking'], ['dietitian-feed', 'Dietitian & rewards'], ['app-outcome', 'Final outcome']];
function Reveal({ children, className = '' }) { const ref = useRef(null); const [visible, setVisible] = useState(false); useEffect(() => { const observer = new IntersectionObserver(([e]) => { if (e.isIntersecting) {
    setVisible(true);
    observer.disconnect();
} }, { threshold: .12 }); if (ref.current)
    observer.observe(ref.current); return () => observer.disconnect(); }, []); return <div ref={ref} className={`${styles.reveal} ${className}`} data-visible={visible}>{children}</div>; }
function Crop({ box, label, className = '' }) { return <svg viewBox={box} role="img" aria-label={label} className={className}><image href="/images/poly-app-outcome.jpg" width="235" height="2049.6"/></svg>; }
function Ovie() { return <svg viewBox="660 370 1380 1360" role="img" aria-label="Ovie, the Poly mascot"><image href="/images/poly-ovie-final.png" width="2732" height="2048"/></svg>; }
function Dashboard() { const [water, setWater] = useState(4); const [day, setDay] = useState(3); const [feeling, setFeeling] = useState(''); const values = [42, 68, 53, 82, 64, 90, 72]; return <Reveal className={styles.dashboard}><div className={styles.dashboardTop}><span>Today, at a glance</span><small>INTERACTIVE PREVIEW · SAMPLE DATA</small></div><div className={styles.widgets}><div className={styles.ring}><svg viewBox="0 0 120 120" aria-label="Calorie log: 1,630 of 1,700 kcal"><circle cx="60" cy="60" r="49"/><circle className={styles.progress} cx="60" cy="60" r="49"/></svg><div><strong>1,630</strong><small>of 1,700 kcal</small></div></div><div className={styles.water}><span>Water log</span><strong>{water * 250}<small> ml</small></strong><div aria-label={`${water} glasses of water`}>{Array.from({ length: 8 }, (_, i) => <i key={i} data-filled={i < water}/>)}</div><button onClick={() => setWater(w => Math.min(8, w + 1))} disabled={water === 8}>+ 250 ml</button><button aria-label="Reset water log" onClick={() => setWater(0)}>Reset</button></div></div><div className={styles.week}><div><span>7-day activity</span><strong>{values[day]} min</strong></div><div className={styles.bars}>{values.map((value, i) => <button key={i} aria-label={`${['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][i]}: ${value} minutes`} aria-pressed={day === i} onClick={() => setDay(i)}><span style={{ height: `${value}%`, transitionDelay: `${i * 80}ms` }}/><small>{['M', 'T', 'W', 'T', 'F', 'S', 'S'][i]}</small></button>)}</div></div><div className={styles.feelings}><span>How do you feel today?</span>{['Comfortable', 'Tired', 'Cramps'].map(label => <button key={label} aria-pressed={feeling === label} onClick={() => setFeeling(label)}>{label}</button>)}</div></Reveal>; }
function Chat({ delay = 150 }) { const [reply, setReply] = useState(false); return <Reveal className={styles.chat}><header><span className={styles.avatar}>P</span><div><strong>Your personal dietitian</strong><small>Guidance, one conversation at a time</small></div></header><p className={styles.chatLabel}>ILLUSTRATIVE CONVERSATION</p>{['What felt manageable this week?', 'Logging lunch was easy. Busy evenings were harder.', 'Let’s start with one small evening check-in. What would make that easier?'].map((message, i) => <div key={message} className={`${styles.bubble} ${i === 1 ? styles.sent : ''}`} style={{ animationDelay: `${i * delay}ms` }}>{message}</div>)}{reply && <div className={`${styles.bubble} ${styles.sent}`} style={{ animationDelay: '0ms' }}>A reminder after dinner would help.</div>}<button className={styles.reply} onClick={() => setReply(!reply)}>{reply ? 'Replay conversation' : 'Try a reply →'}</button></Reveal>; }
const onboarding = [{ box: '10.5 612 48 96', title: 'A friendly first hello', text: 'Ovie welcomes you into a calmer daily routine.' }, { box: '62.5 633 27 57', title: 'Your habits, your pace', text: 'A short introduction keeps the first step approachable.' }, { box: '96.5 633 27 57', title: 'Find everyday inspiration', text: 'Recipes bring the next meal within reach.' }, { box: '130.5 633 27 57', title: 'Understand your body', text: 'Healthcare insights stay close at hand.' }, { box: '164.5 633 27 57', title: 'You are not alone', text: 'Shared experiences make room for belonging.' }, { box: '198.5 633 27 57', title: 'Ready for the everyday', text: 'Move from onboarding into a daily check-in.' }];
function Onboarding() { const [active, setActive] = useState(0); const start = useRef(null); const move = (direction) => setActive(i => (i + direction + onboarding.length) % onboarding.length); return <div className={styles.onboarding}><div className={styles.deck} aria-label="Onboarding screen carousel" tabIndex={0} onKeyDown={e => { if (e.key === 'ArrowRight')
    move(1); if (e.key === 'ArrowLeft')
    move(-1); }} onPointerDown={e => { start.current = e.clientX; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerUp={e => { if (start.current !== null && Math.abs(e.clientX - start.current) > 35)
    move(e.clientX < start.current ? 1 : -1); start.current = null; }} onPointerCancel={() => { start.current = null; }}>{onboarding.map((s, i) => { let offset = (i - active + onboarding.length) % onboarding.length; if (offset > 3)
    offset -= onboarding.length; return <div key={s.title} className={styles.deckScreen} aria-hidden={i !== active} style={{ transform: `translateX(calc(-50% + ${offset * 80}%)) scale(${i === active ? 1 : .9})`, opacity: Math.abs(offset) > 1 ? 0 : i === active ? 1 : .5, zIndex: 10 - Math.abs(offset) }}><Crop box={s.box} label={s.title}/></div>; })}</div><div className={styles.sliderControls}><button aria-label="Previous onboarding screen" onClick={() => move(-1)}>←</button><span aria-live="polite">{String(active + 1).padStart(2, '0')} / 06</span><button aria-label="Next onboarding screen" onClick={() => move(1)}>→</button></div><h4>{onboarding[active].title}</h4><p>{onboarding[active].text}</p></div>; }
export default function PolyAppCaseStudy({ prototype }) {
    const [active, setActive] = useState(chapters[0][0]);
    const [joined, setJoined] = useState(false);
    useEffect(() => { const onScroll = () => { let current = chapters[0][0]; for (const [id] of chapters) {
        const el = document.getElementById(id);
        if (el && el.getBoundingClientRect().top < 320)
            current = id;
    } setActive(current); }; window.addEventListener('scroll', onScroll, { passive: true }); onScroll(); return () => window.removeEventListener('scroll', onScroll); }, []);
    return <div className={`editorial-body ${styles.body}`}><nav className={`case-chapter-nav ${styles.nav}`} aria-label="Case study sections">{chapters.map(([id, label], i) => <a key={id} href={`#${id}`} aria-current={active === id ? 'location' : undefined} className="transition-colors duration-500"><span>{String(i + 1).padStart(2, '0')}</span>{label}</a>)}</nav><article className={styles.article}>
    <section id="mobile-shift" className={styles.chapter}><div className={styles.eyebrow}>01 / THE MOBILE SHIFT</div><h2>Care that fits in your pocket.</h2><p><strong>Poly App</strong> extends the vision of Poly Health, carrying forward its core values of empathy and accessibility in digital healthcare design. The app expands the user experience beyond education by integrating features such as diet and progress tracking, personalized guidance from dietitian, and a reward-based system that motivates sustainable lifestyle improvement for individuals with PCOS (Polycystic Ovary Syndrome).</p><p className={styles.insight}>The original interview surfaced a practical gap: tracking food was hard to sustain, and progress felt difficult to track.</p></section>
    <section id="core-tracking" className={styles.chapter}><div className={styles.eyebrow}>02 / CORE TRACKING</div><h2>Small inputs. A clearer picture.</h2><ul className={styles.flow}><li><strong>Log a meal.</strong><span>Capture food and water while the moment is fresh.</span></li><li><strong>Add movement.</strong><span>Bring activity into the same daily view.</span></li><li><strong>Notice patterns.</strong><span>Review progress alongside how you feel, then choose the next small step.</span></li></ul><Dashboard /></section>
    <section id="dietitian-feed" className={styles.chapter}><div className={styles.eyebrow}>03 / DIETITIAN & REWARDS</div><h2>Consistency needs company.</h2><p>A personal dietitian conversation turns tracking into a starting point for support. Small milestones and a peer community make returning feel encouraging.</p><Chat /><div className={styles.reward}><span>✿</span><div><strong>Every check-in counts.</strong><p>Rewards recognize showing up and building a routine.</p></div></div></section>
    <section id="app-outcome" className={styles.chapter}><div className={styles.eyebrow}>04 / FINAL OUTCOME</div><h2>A daily companion, brought to life.</h2><div className={styles.showcase}><Reveal className={styles.hero}><div className={styles.eyebrow}>POLY APP</div><h3>Diet & Activity<br />Tracking App</h3><p>Your daily habits, with room for being human.</p><div className={styles.heroArt}><div className={styles.floating}><Ovie /></div><Crop box="98 34 58 116" label="Poly App daily tracking phone" className={styles.heroPhone}/><Crop box="163.5 0 57 94" label="Poly App community phone" className={styles.auxPhone}/><Crop box="163.5 100 57 90" label="Poly App recipes phone" className={styles.auxPhoneTwo}/></div></Reveal>
    <div className={styles.feature}><div className={styles.eyebrow}>01 / USER LOG-IN</div><h3>A familiar face from the first tap.</h3><Onboarding /></div>
    <div className={styles.feature}><div className={styles.eyebrow}>02 / HOME & MY DIET</div><h3>Make the everyday visible.</h3><p>A shared view of meals, movement, and hydration. Tap a day or add a glass to explore.</p><Dashboard /><a href="/images/poly-app-outcome.jpg" target="_blank" rel="noreferrer" className={styles.artLink}><Crop box="10 747 210 216" label="Original Poly App home, profile, reward system and calendar screens"/></a></div>
    <div className={styles.feature}><div className={styles.eyebrow}>03 / GUIDANCE & COMMUNITY</div><h3>Someone in your corner.</h3><Chat delay={200}/><Reveal className={styles.community}><span className={styles.eyebrow}>PEER SUPPORT</span><div className={styles.feedEntry}><strong>A small win, shared.</strong><p>A place for recipes, progress, and conversations with people who understand.</p><Crop box="15 1774 73 73" label="A meal shared in the original Poly App community feed"/><button aria-pressed={joined} onClick={() => setJoined(!joined)}>{joined ? '♥ Encouragement sent' : '♡ Send encouragement'}</button></div><div className={styles.feedEntry} style={{ animationDelay: '200ms' }}>A little encouragement can make the next check-in feel easier.</div></Reveal></div>
    <div className={styles.figma}><div><div className={styles.eyebrow}>EXPLORE THE ORIGINAL</div><h3>Take Poly App with you.</h3><div className={styles.scan}><a href={prototype} target="_blank" rel="noreferrer" aria-label="Open the Poly App Figma prototype"><Crop box="43 1956 53 53" label="Original Poly App prototype QR code"/></a><a href={prototype} target="_blank" rel="noreferrer" className={styles.cta}>View on Figma ↗</a></div></div><div className={styles.footerOvie}><Ovie /></div></div>
    </div></section></article></div>;
}
